package org.apache.aries.cdi.container.internal.container;

public enum Op {

	BUNDLE_CLOSE,
	BUNDLE_OPEN,
	CONFIGURATION_CLOSE,
	CONFIGURATION_OPEN,
	CONTAINER_COMPONENT_START,
	CONTAINER_COMPONENT_STOP,
	CONTAINER_INSTANCE_ACTIVATE,
	EXTENSION_CLOSE,
	EXTENSION_OPEN,
	FACTORY_COMPONENT_START,
	FACTORY_COMPONENT_STOP,
	INIT_CLOSE,
	INIT_OPEN,
	SINGLE_COMPONENT_START,
	SINGLE_COMPONENT_STOP,

}
