package org.apache.aries.cdi.container.internal.container;

public enum Op {

	BUNDLE_CLOSE,
	BUNDLE_OPEN,
	CONFIGURATION_CLOSE,
	CONFIGURATION_LISTENER_CLOSE,
	CONFIGURATION_LISTENER_OPEN,
	CONFIGURATION_OPEN,
	CONTAINER_COMPONENT_CLOSE,
	CONTAINER_COMPONENT_OPEN,
	CONTAINER_INSTANCE_CLOSE,
	CONTAINER_INSTANCE_OPEN,
	CONTAINER_REFERENCES_CLOSE,
	CONTAINER_REFERENCES_OPEN,
	EXTENSION_CLOSE,
	EXTENSION_OPEN,
	FACTORY_COMPONENT_CLOSE,
	FACTORY_COMPONENT_OPEN,
	FACTORY_INSTANCE_CLOSE,
	FACTORY_INSTANCE_OPEN,
	INIT_CLOSE,
	INIT_OPEN,
	SINGLE_COMPONENT_CLOSE,
	SINGLE_COMPONENT_OPEN,
	SINGLE_INSTANCE_CLOSE,
	SINGLE_INSTANCE_OPEN,

}
